package edu.univ.erp.util;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.lowagie.text.pdf.draw.LineSeparator;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;

/**
 * TranscriptPdfExporter - exports a compact transcript containing:
 *  Course | Credits | Semester | Year | Final Grade
 *  Also prints CGPA in the header (under student metadata).
 */
public class TranscriptPdfExporter {

    /**
     * Premium exporter: exports a nicely formatted transcript PDF.
     * Note: now accepts cgpaString (e.g. "8.75") to print in header.
     */
    public static void exportPremium(List<TranscriptRow> rows,
                                     File outputPdf,
                                     String studentName,
                                     String studentId,
                                     String program,
                                     String department,
                                     String batch,
                                     File logoFile,
                                     String issueDate,
                                     String cgpaString) throws Exception {

        Document doc = new Document(PageSize.A4, 36, 36, 90, 60);
        PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(outputPdf));
        writer.setPageEvent(new PremiumPageEvent(logoFile, department, issueDate));
        doc.open();

        // Header left
        Paragraph uni = new Paragraph(department == null ? "Institution" : department,
                new Font(Font.HELVETICA, 16, Font.BOLD));
        uni.setSpacingAfter(4f);
        doc.add(uni);

        Paragraph subtitle = new Paragraph("Official Academic Transcript",
                new Font(Font.HELVETICA, 11, Font.NORMAL));
        subtitle.setSpacingAfter(8f);
        doc.add(subtitle);

        // Student info block
        PdfPTable info = new PdfPTable(2);
        info.setWidthPercentage(100);
        info.setWidths(new float[]{3f, 1f});
        info.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        PdfPTable left = new PdfPTable(2);
        left.setWidths(new float[]{1f, 2.5f});
        left.setWidthPercentage(100);
        left.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        left.addCell(createLabelCell("Name:"));
        left.addCell(createValueCell(studentName));
        left.addCell(createLabelCell("Student ID:"));
        left.addCell(createValueCell(studentId));
        left.addCell(createLabelCell("Program:"));
        left.addCell(createValueCell(program));
        left.addCell(createLabelCell("Batch:"));
        left.addCell(createValueCell(batch));

        // CGPA row (only shown if provided)
        left.addCell(createLabelCell("CGPA:"));
        left.addCell(createValueCell(cgpaString == null ? "-" : cgpaString));

        PdfPCell leftWrap = new PdfPCell(left);
        leftWrap.setBorder(Rectangle.NO_BORDER);
        info.addCell(leftWrap);

        PdfPTable right = new PdfPTable(1);
        right.setWidthPercentage(100);
        right.getDefaultCell().setBorder(Rectangle.NO_BORDER);
        right.addCell(createKeyValueCell("Issued on", issueDate));
        right.addCell(createKeyValueCell("Generated by", "Student Portal"));
        PdfPCell rightWrap = new PdfPCell(right);
        rightWrap.setBorder(Rectangle.NO_BORDER);
        info.addCell(rightWrap);

        info.setSpacingAfter(12f);
        doc.add(info);

        // Separator
        LineSeparator ls = new LineSeparator(1f, 100f, Color.BLACK, Element.ALIGN_CENTER, -2f);
        doc.add(new Chunk(ls));
        doc.add(Chunk.NEWLINE);

        // Transcript table: 5 columns
        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3.5f, 0.8f, 1.4f, 0.9f, 1.0f});
        table.setHeaderRows(1);

        addHeader(table, "Course");
        addHeader(table, "Credits");
        addHeader(table, "Semester");
        addHeader(table, "Year");
        addHeader(table, "Final Grade");

        boolean zebra = false;
        Font cellFont = new Font(Font.HELVETICA, 9, Font.NORMAL);
        for (TranscriptRow r : rows) {
            zebra = !zebra;
            java.awt.Color bg = zebra ? new java.awt.Color(248, 248, 248) : java.awt.Color.WHITE;

            addCell(table, r.code + "\n" + r.title, cellFont, bg);
            addCell(table, String.valueOf(r.credits), cellFont, bg);
            addCell(table, r.semester, cellFont, bg);
            addCell(table, String.valueOf(r.year), cellFont, bg);
            addCell(table, r.finalGrade == null ? "N/A" : r.finalGrade, cellFont, bg);
        }

        doc.add(table);

        // Signature block
        PdfPTable bottom = new PdfPTable(1);
        bottom.setWidthPercentage(100);
        bottom.setSpacingBefore(12f);

        PdfPTable sig = new PdfPTable(1);
        sig.setWidthPercentage(100);
        sig.getDefaultCell().setBorder(Rectangle.NO_BORDER);
        PdfPCell sigBox = new PdfPCell();
        sigBox.setBorder(Rectangle.NO_BORDER);
        sigBox.setPaddingTop(6f);
        sigBox.addElement(new Phrase("Registrar", new Font(Font.HELVETICA, 10, Font.BOLD)));
        sigBox.addElement(new Phrase("\n\n__________________________", new Font(Font.HELVETICA, 9, Font.NORMAL)));
        sigBox.addElement(new Phrase("\nThis is a system-generated transcript.", new Font(Font.HELVETICA, 8, Font.ITALIC)));
        sig.addCell(sigBox);

        PdfPCell sigWrap = new PdfPCell(sig);
        sigWrap.setBorder(Rectangle.NO_BORDER);
        bottom.addCell(sigWrap);

        doc.add(bottom);

        doc.close();
    }

    // ---------- helpers ----------
    private static PdfPCell createLabelCell(String label) {
        PdfPCell c = new PdfPCell(new Phrase(label, new Font(Font.HELVETICA, 10, Font.BOLD)));
        c.setBorder(Rectangle.NO_BORDER);
        c.setHorizontalAlignment(Element.ALIGN_LEFT);
        c.setPadding(2f);
        return c;
    }

    private static PdfPCell createValueCell(String v) {
        PdfPCell c = new PdfPCell(new Phrase(v == null ? "" : v, new Font(Font.HELVETICA, 9, Font.NORMAL)));
        c.setBorder(Rectangle.NO_BORDER);
        c.setHorizontalAlignment(Element.ALIGN_LEFT);
        c.setPadding(2f);
        return c;
    }

    private static PdfPCell createKeyValueCell(String key, String value) {
        PdfPTable t = new PdfPTable(1);
        t.setWidthPercentage(100);
        t.getDefaultCell().setBorder(Rectangle.NO_BORDER);
        t.addCell(new PdfPCell(new Phrase(key, new Font(Font.HELVETICA, 8, Font.BOLD))));
        PdfPCell v = new PdfPCell(new Phrase(value == null ? "" : value, new Font(Font.HELVETICA, 9, Font.NORMAL)));
        v.setBorder(Rectangle.NO_BORDER);
        t.addCell(v);
        PdfPCell wrapper = new PdfPCell(t);
        wrapper.setBorder(Rectangle.NO_BORDER);
        return wrapper;
    }

    private static void addHeader(PdfPTable t, String text) {
        PdfPCell c = new PdfPCell(new Phrase(text, new Font(Font.HELVETICA, 10, Font.BOLD)));
        c.setHorizontalAlignment(Element.ALIGN_CENTER);
        c.setBackgroundColor(new java.awt.Color(230, 230, 230));
        c.setPadding(6f);
        t.addCell(c);
    }

    private static void addCell(PdfPTable t, String text, Font f, java.awt.Color bg) {
        PdfPCell c = new PdfPCell(new Phrase(text == null ? "" : text, f));
        c.setPadding(6f);
        c.setBackgroundColor(bg);
        c.setUseAscender(true);
        c.setUseDescender(true);
        t.addCell(c);
    }

    // ---------- row model ----------
    public static class TranscriptRow {
        public final String code;
        public final String title;
        public final int credits;
        public final String semester;
        public final int year;
        public final String finalGrade;

        // compact row model (only fields we use now)
        public TranscriptRow(String code, String title, int credits, String semester, int year, String finalGrade) {
            this.code = code;
            this.title = title;
            this.credits = credits;
            this.semester = semester;
            this.year = year;
            this.finalGrade = finalGrade;
        }
    }

    // ---------- premium page event (logo + watermark) ----------
    private static class PremiumPageEvent extends PdfPageEventHelper {
        private final File logoFile;
        private final String instituteName;
        private final String issueDate;

        PremiumPageEvent(File logoFile, String instituteName, String issueDate) {
            this.logoFile = logoFile;
            this.instituteName = instituteName;
            this.issueDate = issueDate;
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            try {
                PdfContentByte cb = writer.getDirectContent();
                // page number
                Font f = new Font(Font.HELVETICA, 9, Font.NORMAL);
                Phrase footer = new Phrase("Page " + writer.getPageNumber(), f);
                ColumnText.showTextAligned(cb, Element.ALIGN_CENTER, footer,
                        (document.right() + document.left()) / 2,
                        document.bottom() - 20, 0);

                // logo top-right (if provided)
                if (logoFile != null && logoFile.exists()) {
                    Image logo = Image.getInstance(logoFile.getAbsolutePath());
                    float max = Math.max(logo.getWidth(), logo.getHeight());
                    float scale = 60f / max;
                    logo.scaleAbsolute(logo.getWidth() * scale, logo.getHeight() * scale);
                    float x = document.right() - logo.getScaledWidth();
                    float y = document.top() + 10;
                    logo.setAbsolutePosition(x, y);
                    cb.addImage(logo);
                }

                // watermark
                PdfGState gs = new PdfGState();
                gs.setFillOpacity(0.07f);
                cb.saveState();
                cb.setGState(gs);
                cb.beginText();
                BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.EMBEDDED);
                cb.setFontAndSize(bf, 60f);
                cb.setRGBColorFill(200, 200, 200);
                float xcenter = (document.right() + document.left()) / 2;
                float ycenter = (document.top() + document.bottom()) / 2;
                cb.showTextAligned(Element.ALIGN_CENTER, "UNOFFICIAL", xcenter, ycenter, 45);
                cb.endText();
                cb.restoreState();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
}
